# Generated by Django 5.2.7 on 2025-11-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'In Cart'), ('ordered', 'Ordered')], default='cart', max_length=10),
        ),
    ]
