# Generated by Django 5.2.7 on 2025-11-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='coupon_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='discounted_bill',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
